"""SQLAlchemy ORM models for signals, trades, and metrics."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    create_engine,
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass


class Signal(Base):
    """A trading signal generated by the analysis pipeline."""

    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    symbol = Column(String(20), nullable=False, index=True)
    exchange = Column(String(10), default="NSE")
    sentiment = Column(String(10), nullable=False)  # BULLISH, BEARISH, NEUTRAL
    confidence = Column(Float, nullable=False)
    strength = Column(String(10))  # STRONG, MODERATE, WEAK

    # Confidence breakdown
    news_strength = Column(Float)
    signal_alignment = Column(Float)
    market_confirmation = Column(Float)
    liquidity_score = Column(Float)
    risk_penalty = Column(Float)

    # Context
    strategy_name = Column(String(50))
    key_drivers = Column(Text)  # JSON array
    risks = Column(Text)  # JSON array
    summary = Column(Text)
    time_horizon = Column(String(20))  # intraday, swing, positional

    # Status
    status = Column(String(20), default="pending")  # pending, approved, rejected, expired
    final_score = Column(Float)
    regime = Column(String(20))  # bull, bear, range_bound, choppy

    # Relationship
    trades = relationship("Trade", back_populates="signal")


class Trade(Base):
    """A trade executed based on a signal."""

    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, ForeignKey("signals.id"), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    symbol = Column(String(20), nullable=False, index=True)
    exchange = Column(String(10), default="NSE")

    # Order details
    direction = Column(String(10), nullable=False)  # BUY, SELL
    quantity = Column(Integer, nullable=False)
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float)
    target_price = Column(Float)
    order_type = Column(String(10))  # MARKET, LIMIT

    # Execution
    order_id = Column(String(50))  # Kite order ID or paper order ID
    execution_mode = Column(String(10))  # paper, live
    slippage_bps = Column(Float)

    # Exit
    exit_price = Column(Float)
    exit_at = Column(DateTime)
    exit_reason = Column(String(50))  # stop_loss, target, time_based, confidence_decay, manual

    # Performance
    pnl = Column(Float)  # Realized PnL in INR
    pnl_pct = Column(Float)  # PnL as percentage
    holding_duration_min = Column(Integer)

    # Strategy
    strategy_name = Column(String(50))
    position_size_method = Column(String(20))

    # Relationship
    signal = relationship("Signal", back_populates="trades")


class DailyMetric(Base):
    """Daily aggregate performance metrics."""

    __tablename__ = "daily_metrics"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(DateTime, nullable=False, unique=True, index=True)
    execution_mode = Column(String(10))  # paper, live

    # Trade stats
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)

    # PnL
    total_pnl = Column(Float, default=0.0)
    max_drawdown = Column(Float, default=0.0)
    max_capital_deployed = Column(Float, default=0.0)

    # Signal stats
    signals_generated = Column(Integer, default=0)
    signals_approved = Column(Integer, default=0)
    signals_rejected = Column(Integer, default=0)

    # Quality
    win_rate = Column(Float)
    profit_factor = Column(Float)
    sharpe_ratio = Column(Float)
    avg_pnl_per_trade = Column(Float)


class PositionState(Base):
    """Persisted open position state — survives app restarts."""

    __tablename__ = "position_state"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, unique=True, index=True)
    exchange = Column(String(10), default="NSE")
    direction = Column(String(10), nullable=False)
    quantity = Column(Integer, nullable=False)
    entry_price = Column(Float, nullable=False)
    current_price = Column(Float, default=0.0)
    stop_loss = Column(Float)
    target_price = Column(Float)
    order_id = Column(String(50))
    signal_id = Column(Integer)
    strategy_name = Column(String(50))
    entry_time = Column(DateTime)
    unrealized_pnl = Column(Float, default=0.0)
    capital_deployed = Column(Float, default=0.0)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class AutoSellTriggerState(Base):
    """Persisted auto-sell trigger — survives app restarts."""

    __tablename__ = "auto_sell_trigger_state"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, unique=True, index=True)
    position_entry_price = Column(Float, nullable=False)
    position_direction = Column(String(10), nullable=False)
    stop_loss = Column(Float, nullable=False)
    target_price = Column(Float, nullable=False)
    trailing_stop_pct = Column(Float, default=1.5)
    max_hold_minutes = Column(Integer, default=90)
    confidence_floor = Column(Float, default=0.5)
    structure_break_threshold = Column(Float, default=-1.0)
    created_at = Column(DateTime, nullable=False)
    highest_price = Column(Float, default=0.0)
    lowest_price = Column(Float, default=999999.0)
    is_active = Column(Boolean, default=True)
    exit_strategy = Column(Text, default="")
    invalidation_condition = Column(Text, default="")
    # GTT exchange-level protection
    gtt_trigger_id = Column(String(50), default="")
    gtt_status = Column(String(20), default="pending")
    gtt_stop_price = Column(Float, default=0.0)
    gtt_last_updated = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class PendingSignalState(Base):
    """Persisted pending signal awaiting user approval."""

    __tablename__ = "pending_signal_state"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(String(20), nullable=False, unique=True, index=True)
    signal_json = Column(Text, nullable=False)
    created_at = Column(DateTime, nullable=False)
    expiry_minutes = Column(Integer, default=15)
    telegram_message_id = Column(Integer)
    status = Column(String(20), default="pending")
    action = Column(String(20))


class AppState(Base):
    """Generic key-value store for app-level state (kill switch, portfolio counters)."""

    __tablename__ = "app_state"

    id = Column(Integer, primary_key=True, autoincrement=True)
    key = Column(String(50), nullable=False, unique=True, index=True)
    value = Column(Text, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
